//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_IS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public long ID_Book { get; set; }
        public string Book_Name { get; set; }
        public string ISBN { get; set; }
        public short Year { get; set; }
        public Nullable<long> ID_Author { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual UserBook UserBook { get; set; }
    }
}
